title: Zos' stuff
author: zos-goatherd
email: zos_the_goatherd@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  my first attempt at a web page, I will be using this for practice and not much else
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
mastadon_username:
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
